name: lipobatterymanager
description: A new Flutter project.

publish_to: "none"

version: 2.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  material_design_icons_flutter: ^5.0.6595
  flutter_boxicons: ^3.0.0
  provider: ^6.0.4
  localstorage: ^4.0.0+1
  url_launcher: ^6.1.6
  numberpicker: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#1a1a1a"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
